services:
  - type: web
    name: cleancare-pro-api
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && NODE_ENV=production node server-laundry.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - fromGroup: cleancare-secrets
      - key: MONGODB_DATABASE
        value: cleancare_pro
      - key: ALLOWED_ORIGINS
        value: https://cleancare-pro-frontend.onrender.com

  - type: web
    name: cleancare-pro-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - fromGroup: cleancare-secrets
      - key: VITE_API_BASE_URL
        value: https://cleancare-pro-api.onrender.com/api
      - key: VITE_APP_NAME
        value: CleanCare Pro
      - key: VITE_APP_URL
        value: https://cleancare-pro-frontend.onrender.com

envVarGroups:
  - name: cleancare-secrets
    envVars:
      - key: MONGODB_URI
        value: # your mongo URI
      - key: MONGODB_USERNAME
        value: # your mongo username
      - key: MONGODB_PASSWORD
        value: # your mongo password
      - key: MONGODB_CLUSTER
        value: # your cluster
      - key: DVHOSTING_API_KEY
        value: # sms key
      - key: JWT_SECRET
        value: # secret
      - key: VITE_DVHOSTING_API_KEY
        value: # frontend key
      - key: VITE_GOOGLE_MAPS_API_KEY
        value: # map key
